# Generated by Django 5.1.3 on 2024-11-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='bio',
            field=models.TextField(default='', verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='dob',
            field=models.DateField(default='1970-01-01', verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='fastest_guess',
            field=models.TimeField(default=None, verbose_name='time of fastest guess'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(default='anonymous_user', max_length=60, unique=True, verbose_name='username'),
        ),
    ]
