# Generated by Django 5.1.3 on 2024-11-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_playerprofile_bio_alter_playerprofile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='fastest_guess',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='time of fastest guess'),
        ),
    ]
