# Generated by Django 5.1.3 on 2024-11-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_playerprofile_bio_alter_playerprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='bio',
            field=models.TextField(default='No information written', verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='profile_picture',
            field=models.ImageField(default='default-profile-icon.png', upload_to='profile-pictures/', verbose_name='Profile picture'),
        ),
    ]
