# Generated by Django 5.1.3 on 2024-11-23 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_playerprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friendship_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of friendship creation'),
        ),
    ]
