# Generated by Django 5.1.3 on 2024-11-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_friend_friendship_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friendship_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of friendship creation'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Account creation date'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='profile_picture',
            field=models.ImageField(default='defaults/profile-icon.png', upload_to='profile-pictures/', verbose_name='Profile picture'),
        ),
    ]
