# Generated by Django 5.1.3 on 2024-11-24 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_friend_friendship_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='Username')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='Account creation date')),
                ('profile_picture', models.ImageField(default='defaults/profile-icon.png', upload_to='profile-pictures/', verbose_name='Profile picture')),
                ('is_guest', models.BooleanField(default=False, verbose_name='Is guest profile')),
                ('dob', models.DateField(default='1970-01-01', verbose_name='Date of birth')),
                ('bio', models.TextField(default='No information written', verbose_name='Bio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='daily_streak',
            field=models.IntegerField(default=0, verbose_name='Highest daily streak'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='is_guest',
            field=models.BooleanField(default=False, verbose_name='Is guest profile'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_played',
            field=models.DateField(default='1970-01-01', verbose_name='Last played'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='dob',
            field=models.DateField(default='1970-01-01', verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Player account'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(max_length=60, unique=True, verbose_name='Username'),
        ),
    ]
