# Generated by Django 5.1.3 on 2024-11-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_guestprofile_playerprofile_daily_streak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofile',
            name='dob',
        ),
    ]
