# Generated by Django 5.1.3 on 2024-11-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_guestprofile_email_and_more'),
        ('game', '0010_remove_guess_game_guess_puzzle_type_only_one_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestProfile',
        ),
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
