# Generated by Django 5.1.3 on 2024-11-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_guestprofile_user_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_guest',
        ),
    ]
