# Generated by Django 5.1.3 on 2024-11-30 01:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_playerprofile_daily_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(default=uuid.UUID('b0032f9f-0b8b-4d01-8ba2-fb81c626eb76'), max_length=60, unique=True, verbose_name='Username'),
        ),
    ]
