# Generated by Django 5.1.3 on 2024-12-09 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_playerprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='fastest_guess',
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(default=uuid.UUID('49691837-376b-4850-9732-d968b334584f'), max_length=60, unique=True, verbose_name='Username'),
        ),
    ]
