# Generated by Django 5.1.3 on 2024-12-09 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_playerprofile_fastest_guess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(default=uuid.UUID('9a264041-315c-4f49-b2a9-a3e876fece6b'), max_length=60, unique=True, verbose_name='Username'),
        ),
    ]
