# Generated by Django 5.1.3 on 2024-12-09 20:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_playerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(default=uuid.UUID('6e8ee446-41dc-4c66-b7be-321b893c3128'), max_length=60, unique=True, verbose_name='Username'),
        ),
    ]
