# Generated by Django 5.1.3 on 2024-12-09 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_playerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(default=uuid.UUID('ffc5ad23-90e5-4e58-b480-069a76480e7d'), max_length=60, unique=True, verbose_name='Username'),
        ),
    ]
