# Generated by Django 5.1.3 on 2024-12-10 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_playerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(default=uuid.UUID('be863df1-085b-49fc-b178-b543f69cdca7'), max_length=60, unique=True, verbose_name='Username'),
        ),
    ]
