# Generated by Django 5.1.3 on 2024-12-10 22:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_playerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(default=uuid.UUID('b03b393d-45f5-4bec-8cf6-2cf40a86d262'), max_length=60, unique=True, verbose_name='Username'),
        ),
    ]
