# Generated by Django 5.1.3 on 2024-12-10 22:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_playerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(default=uuid.UUID('39f94be8-5ab4-41a6-be01-36f98378ce14'), max_length=60, unique=True, verbose_name='Username'),
        ),
    ]
