# Generated by Django 5.1.3 on 2024-11-22 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_playerprofile_bio_alter_playerprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Item price')),
                ('name', models.TextField(default='', verbose_name='Item name')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Item image')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Time of comment written')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Comment image')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.playerprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item', verbose_name='Item where comment is written')),
            ],
        ),
    ]
