# Generated by Django 5.1.3 on 2024-11-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_guess_did_guess_correctly_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guess',
            name='game_guess_profile_type_only_one_owner',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='owner_guest',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='owner_profile_type',
        ),
    ]
