# Generated by Django 5.1.3 on 2024-11-25 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_guestprofile_email_and_more'),
        ('game', '0006_remove_guess_game_guess_profile_type_only_one_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='owner_guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guestprofile', verbose_name='Guest profile'),
        ),
        migrations.AddField(
            model_name='guess',
            name='owner_profile_type',
            field=models.CharField(choices=[('P', 'PlayerProfile'), ('G', 'GuestProfile')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='guess',
            name='owner_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.playerprofile', verbose_name='Player profile'),
        ),
        migrations.AddConstraint(
            model_name='guess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_guest_id__isnull', True), ('owner_profile_type', 'G')), models.Q(('owner_player_id__isnull', True), ('owner_profile_type', 'P')), _connector='OR'), name='game_guess_profile_type_only_one_owner'),
        ),
    ]
