# Generated by Django 5.1.3 on 2024-11-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_guestprofile_email_and_more'),
        ('game', '0007_guess_owner_guest_guess_owner_profile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='owner_daily_puzzle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game.dailypuzzle', verbose_name='Daily puzzle'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='owner_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guestprofile', verbose_name='Guest profile'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='owner_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.playerprofile', verbose_name='Player profile'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='owner_practice_puzzle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game.practicepuzzle', verbose_name='Practice puzzle'),
        ),
    ]
