# Generated by Django 5.1.3 on 2024-11-25 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_guess_owner_daily_puzzle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='owner_daily_puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.dailypuzzle', verbose_name='Daily puzzle'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='owner_practice_puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.practicepuzzle', verbose_name='Practice puzzle'),
        ),
    ]
