# Generated by Django 5.1.3 on 2024-11-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_guess_owner_daily_puzzle_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guess',
            name='game_guess_puzzle_type_only_one_owner',
        ),
        migrations.RemoveConstraint(
            model_name='guess',
            name='game_guess_profile_type_only_one_owner',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='owner_guest',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='owner_profile_type',
        ),
    ]
