# Generated by Django 5.1.3 on 2024-11-27 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_guess_game_guess_puzzle_type_only_one_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guess',
            old_name='owner_player',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='guess',
            name='owner_daily_puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.dailypuzzle', verbose_name='Daily puzzle'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='owner_practice_puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.practicepuzzle', verbose_name='Practice puzzle'),
        ),
    ]
