# Generated by Django 5.1.3 on 2024-12-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_guess_did_guess_correctly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='num_guesses',
            field=models.IntegerField(default=0, verbose_name='Number of guesses made'),
        ),
    ]
