# Generated by Django 5.1.3 on 2024-12-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_guess_num_guesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='correctly_guessed',
            field=models.BooleanField(default=False, verbose_name='Correctly guessed price'),
        ),
    ]
