# Generated by Django 5.1.3 on 2024-12-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_guess_closeness_guess_five_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='daily_item',
            field=models.BooleanField(default=True, verbose_name='Potential daily item'),
        ),
        migrations.AddField(
            model_name='item',
            name='practice_item',
            field=models.BooleanField(default=False, verbose_name='Potential practice item'),
        ),
        migrations.AddField(
            model_name='item',
            name='used_as_daily',
            field=models.BooleanField(default=False, verbose_name='Used as daily item'),
        ),
    ]
