# Generated by Django 5.1.3 on 2024-12-10 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_itemimage_item_daily_item_item_practice_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.itemimage', verbose_name='Item image'),
        ),
    ]
