# Generated by Django 5.1.3 on 2024-12-11 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_itemimage_image_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PracticePuzzle',
            new_name='NormalPuzzle',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='practice_item',
            new_name='used_as_normal',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='practice_puzzle',
        ),
        migrations.RemoveField(
            model_name='item',
            name='daily_item',
        ),
        migrations.AddField(
            model_name='guess',
            name='finished_guess',
            field=models.BooleanField(default=False, verbose_name='Finished guessing'),
        ),
        migrations.AddField(
            model_name='guess',
            name='normal_puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.normalpuzzle', verbose_name='Normal Puzzle'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(default='', verbose_name='Comment message'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(default='Item name', verbose_name='Item name'),
        ),
        migrations.AddConstraint(
            model_name='itemimage',
            constraint=models.CheckConstraint(condition=models.Q(('image_url__isnull', True), ('image_file__isnull', True), _connector='XOR'), name='both_fields_cannot_be_null_or_exist'),
        ),
    ]
